[tool.ruff]
line-length = 79
indent-width = 4
target-version = "py310"
unsafe-fixes = false
preview = false
fix = true

[tool.ruff.lint]
extend-select = ["I", "COM812"]  # Move COM812 here
extend-ignore = ["C90", "D", "E111"]
# Remove the duplicate select line

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["CPY001"]

[tool.ruff.format]
docstring-code-format = true
skip-magic-trailing-comma = false
