# @package _global_

# Hyperparameters for the synthetic dataset
data:
  n_samples: 1000
  n_features: 10
  n_states: 5
  sequence_length: 50
  transition_bias: 0.9 # High value makes states persist

# Model hyperparameters
model:
  n_states: ${data.n_states}
  n_features: ${data.n_features}
  rnn_hidden_size: 64
  embedding_dim: 16
  transition_hidden_size: 32
  emission_hidden_size: 32

# Trainer hyperparameters
trainer:
  learning_rate: 1e-3
  batch_size: 32
  n_epochs: 50
  gumbel_tau: 1.0 # Initial Gumbel-Softmax temperature
  tau_decay: 0.995 # Multiplicative decay factor for tau
  min_tau: 0.1 # Minimum value for tau
  wandb_project: "dssm_pytorch"
  wandb_entity: null # Your wandb entity, or null
  device: "cuda" # "cuda" or "cpu"
